### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by loversama** [1b5d/llm-api#11]
I am getting this issue running it in docker with default stuff, torch isn't in the requirements or the default Dockerfile?

>  Traceback (most recent call last):
>   File "/llm-api/./app/main.py", line 14, in <module>
>     from app.llms import get_model_class
>   File "/llm-api/app/llms/__init__.py", line 7, in <module>
>     from .gptq_llama.gptq_llama import GPTQLlamaLLM
>   File "/llm-api/app/llms/gptq_llama/__init__.py", line 4, in <module>
>     from .gptq_llama import GPTQLlamaLLM
>   File "/llm-api/app/llms/gptq_llama/gptq_llama.py", line 10, in <module>
>     import torch  # pylint: disable=import-error
> ModuleNotFoundError: No module named 'torch'

I have messed around trying to inject all the requirements but I am wondering if I am missing something, I'd have thought the default packaged docker-compose file should just work out of the box CPU wise right?

I can bypass all of that by adding:

>  RUN pip install torch safetensors transformers

To the Dockerfile, but then get this issue:

> Traceback (most recent call last):
>   File "/llm-api/app/llms/gptq_llama/gptq_llama.py", line 21, in <module>
>     from .GPTQforLLaMa import quant
> ImportError: cannot import name 'quant' from 'app.llms.gptq_llama.GPTQforLLaMa' (unknown location)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/llm-api/./app/main.py", line 14, in <module>
>     from app.llms import get_model_class
>   File "/llm-api/app/llms/__init__.py", line 7, in <module>
>     from .gptq_llama.gptq_llama import GPTQLlamaLLM
>   File "/llm-api/app/llms/gptq_llama/__init__.py", line 4, in <module>
>     from .gptq_llama import GPTQLlamaLLM
>   File "/llm-api/app/llms/gptq_llama/gptq_llama.py", line 24, in <module>
>     raise ImportError(
> ImportError: the GPTQ-for-LLaMa lib is missing, please install it first

I was hoping with it using Docker it would have all the dependencies installed automatically, am I doing it wrong?

**Comment by 1b5d** [comment]
Could you please elaborate how exactly are you running it and which image are you using?

**Comment by 1b5d** [comment]
@loversama you are right about the GPTQ-for-LLaMa error, I was able to reproduce it locally.

I pushed a new version of the last image, you can pull it and try again

**Comment by loversama** [comment]
Awesome, thank you I will take a look, as for my setup I just copied someone else's configuration as a quick test but I will report back after doing some more tests..

**Comment by 1b5d** [comment]
Closing this as it should be resolved by now
