### ISSUE TITLE
How to train model with my data - can i use api?

### ISSUE THREAD

**Issue by michalbrzezinskiorg** [1b5d/llm-api#13]
Maybe it is siły question but as a developer experimentong with tools i would like to have oprion to upload my data (ebooks etc) in plain text and metadata and train model with it to building private knowledge with AI agent. Is that possible to count on it?

**Comment by 1b5d** [comment]
That's possible with this API or other models API, but not with the model alone, you need other tools to augment the model with large contexts, for example you can use langchain
